version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "43695:8080"  # Map container's port 8080 to host's port 43695
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080  # ASP.NET Core application listening on port 8080
    networks:
      - mynetwork

  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "56088:80"  # Map container's port 80 to host's port 56088
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80  # ASP.NET Core application listening on port 80
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
